<?php

/* custom routes generated by CRUD */
Route::group(array('prefix' => 'admin', 'middleware' => ['web','admin'],'as'=>'admin.'), function () {Route::resource('legends', 'LegendsController');
	Route::get('legends/{id}/delete', array('as' => 'legends.delete', 'uses' => 'LegendsController@getDelete'));
	Route::get('legends/{id}/confirm-delete', array('as' => 'legends.confirm-delete', 'uses' => 'LegendsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','admin'],'as'=>'admin.'), function () {Route::resource('legends', 'LegendsController');
	Route::get('legends/{id}/delete', array('as' => 'legends.delete', 'uses' => 'LegendsController@getDelete'));
	Route::get('legends/{id}/confirm-delete', array('as' => 'legends.confirm-delete', 'uses' => 'LegendsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','admin'],'as'=>'admin.'), function () {Route::resource('legends', 'LegendsController');
	Route::get('legends/{id}/delete', array('as' => 'legends.delete', 'uses' => 'LegendsController@getDelete'));
	Route::get('legends/{id}/confirm-delete', array('as' => 'legends.confirm-delete', 'uses' => 'LegendsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','admin'],'as'=>'admin.'), function () {Route::resource('legends', 'LegendsController');
	Route::get('legends/{id}/delete', array('as' => 'legends.delete', 'uses' => 'LegendsController@getDelete'));
	Route::get('legends/{id}/confirm-delete', array('as' => 'legends.confirm-delete', 'uses' => 'LegendsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','admin'],'as'=>'admin.'), function () {Route::resource('legends', 'LegendsController');
	Route::get('legends/{id}/delete', array('as' => 'legends.delete', 'uses' => 'LegendsController@getDelete'));
	Route::get('legends/{id}/confirm-delete', array('as' => 'legends.confirm-delete', 'uses' => 'LegendsController@getModalDelete'));
});Route::group(array('prefix' => 'admin', 'middleware' => ['web','admin'],'as'=>'admin.'), function () {Route::resource('legends', 'LegendsController');
	Route::get('legends/{id}/delete', array('as' => 'legends.delete', 'uses' => 'LegendsController@getDelete'));
	Route::get('legends/{id}/confirm-delete', array('as' => 'legends.confirm-delete', 'uses' => 'LegendsController@getModalDelete'));
});